services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: taskoverflow

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./todo:/app/todo
      - ./credentials:/root/.aws/credentials
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg://administrator:verySecretPassword@database:5432/taskoverflow
    ports:
      - "6400:6400"
    depends_on:
      - database
    command: pipx run poetry run flask --app todo run --debug --host 0.0.0.0 --port 6401
